controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - right_finger_joint
    interface_name: effort
