controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
        publish_rate: 50.0
        joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6
          - joint_7
        interfaces:
          - position
          - velocity
          - effort

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6
          - joint_7
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
        state_publish_rate: 50.0
        action_monitor_rate: 20.0
        allow_partial_joints_goal: false
        constraints:
          stopped_velocity_tolerance: 0.2
          goal_time: 0.0
          joint_1:
            trajectory: 0.2
            goal: 0.1
          joint_2:
            trajectory: 0.2
            goal: 0.1
          joint_3:
            trajectory: 0.2
            goal: 0.1
          joint_4:
            trajectory: 0.2
            goal: 0.1
          joint_5:
            trajectory: 0.2
            goal: 0.1
          joint_6:
            trajectory: 0.2
            goal: 0.1
          joint_7:
            trajectory: 0.2
            goal: 0.1

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    fault_controller:
      type: picknik_reset_fault_controller/PicknikResetFaultController

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    allow_stalling: true
